version: "3.8"

services:
  backend:
    build: ./backend
    command: gunicorn classroomconversation.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env.prod
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static_volume:/staticfiles
      - media_volume:/mediafiles
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - backend
volumes:
  postgres_data:
  static_volume:
  media_volume:
