version: "3.8"

services:
  backend:
    build: ./backend
    command: gunicorn classroomconversation.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static_volume:/staticfiles
      - media_volume:/mediafiles

  frontend:
    image: node:8.9
    build: ./frontend
    volumes:
      - frontend_volume:/build
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - frontend_volume:/home/app/web/frontend
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - backend
      - frontend
volumes:
  postgres_data:
  static_volume:
  frontend_volume:
  media_volume:
# volumes:
#   - postgres_data:/var/lib/postgresql/data/
# env_file:
#   - ./.env.prod.db
# .env.prod:
#   DEBUG=0
#   SECRET_KEY=change_me
#   DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#   SQL_ENGINE=django.db.backends.postgresql
#   SQL_DATABASE=hello_django_prod
#   SQL_USER=hello_django
#   SQL_PASSWORD=hello_django
#   SQL_HOST=db
#   SQL_PORT=5432
#   DATABASE=postgres
#   .env.prod.db:
#   POSTGRES_USER=hello_django
#   POSTGRES_PASSWORD=hello_django
#   POSTGRES_DB=hello_django_prod
#   postgres_data:
#   static_volume:

# docker-compose up -d
# docker-compose exec backend python manage.py migrate --noinput
# docker-compose exec backend python manage.py createsuperuser

#
# $ docker-compose -f docker-compose.yml down -v
# $ docker-compose -f docker-compose.yml up -d --build
# --remove-orphans
# $ docker-compose -f docker-compose.yml exec web python manage.py migrate --noinput
# $ docker-compose -f docker-compose.yml exec web python manage.py collectstatic --no-input --clear

#1. migrate
#2. collectstatic
#3. create admin user

#TODO:
#- prod and dev
#- env files

