version: "3.8"

services:
  backend:
    build: ./backend
    command: gunicorn classroomconversation.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static_volume:/staticfiles
      - media_volume:/mediafiles

  frontend:
    image: node:8.9
    build: ./frontend
    volumes:
      - frontend_volume:/build
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/web/staticfiles
      - frontend_volume:/home/app/web/frontend
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - backend
      - frontend
volumes:
  postgres_data:
  static_volume:
  frontend_volume:
  media_volume:
