# Generated by Django 3.1a1 on 2020-05-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='uniform_probability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='json',
            field=models.JSONField(blank=True),
        ),
    ]
